# Generated by Django 4.1 on 2024-03-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f5', models.CharField(max_length=30)),
                ('f6', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parent1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(max_length=30)),
                ('f2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f3', models.CharField(max_length=30)),
                ('f4', models.CharField(max_length=30)),
            ],
        ),
    ]
